export enum NotificationType {
  CONTRACT_CREATED   = 'CONTRACT_CREATED',
  CONTRACT_APPROVED  = 'CONTRACT_APPROVED',
  INVOICE_GENERATED  = 'INVOICE_GENERATED',
  INVOICE_DUE_SOON   = 'INVOICE_DUE_SOON',
  PAYMENT_RECEIVED   = 'PAYMENT_RECEIVED',
  PAYMENT_OVERDUE    = 'PAYMENT_OVERDUE',
  REFUND_REQUESTED   = 'REFUND_REQUESTED',
  SYSTEM             = 'SYSTEM'
}