CREATE TABLE notifications(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    title VARCHAR(150) NOT NULL,
    message VARCHAR(254) NOT NULL,
    type VARCHAR(30) NOT NULL,

    is_read BOOLEAN DEFAULT FALSE,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

    user_id BIGINT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
);