CREATE TABLE gateway_transactions(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    external_id VARCHAR(254) NOT NULL UNIQUE,
    gateway_name VARCHAR(254) NOT NULL,
    raw_response TEXT,
    amount DECIMAL(15, 2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

    payment_id BIGINT NOT NULL UNIQUE,

    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE
);