package com.raul.backend.enums;

public enum AuditAction {
    CONTRACT_CREATED, CONTRACT_UPDATED, CONTRACT_CANCELLED,
    INVOICE_CREATED, INVOICE_CANCELLED,
    PAYMENT_CREATED, PAYMENT_DELETED,
    REFUND_REQUESTED, REFUND_APPROVED, REFUND_REJECTED,
    CLIENT_CREATED, CLIENT_UPDATED, CLIENT_DEACTIVATED,
    USER_CREATED, USER_UPDATED,INVOICE_DUE_SOON,
    SYSTEM_ERROR
}
